<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { adminAPI } from '@/api/admin'
const loading=ref(false); const saving=ref(false); const form=ref<any>({ risk_control:{} })
function lines(v:any){ return Array.isArray(v)?v.join('\n'):'' }
function split(v:string){ return String(v||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean) }
const guilds=ref(''), channels=ref(''), roles=ref(''), blocked=ref('')
async function load(){ loading.value=true; try{ const res=await adminAPI.getDiscordBotSettings(); form.value=res.data?.data||{risk_control:{}}; form.value.risk_control ||= {}; guilds.value=lines(form.value.risk_control.allowed_guild_ids); channels.value=lines(form.value.risk_control.allowed_channel_ids); roles.value=lines(form.value.risk_control.allowed_role_ids); blocked.value=lines(form.value.risk_control.blocked_user_ids) } finally{loading.value=false} }
async function save(){ saving.value=true; try{ form.value.risk_control.allowed_guild_ids=split(guilds.value); form.value.risk_control.allowed_channel_ids=split(channels.value); form.value.risk_control.allowed_role_ids=split(roles.value); form.value.risk_control.blocked_user_ids=split(blocked.value); await adminAPI.updateDiscordBotSettings(form.value); await load(); alert('已保存') } finally{saving.value=false} }
onMounted(load)
</script>
<template><div class="space-y-4"><div><h1 class="text-2xl font-semibold">Discord 风控设置</h1><p class="text-sm text-slate-500">控制频道白名单、身份组权限、黑名单和用户操作限频。</p></div><div v-if="!loading" class="space-y-4 rounded-xl border bg-white p-4"><label class="inline-flex items-center gap-2"><input type="checkbox" v-model="form.risk_control.enabled" />启用 Discord 风控</label><div class="grid gap-4 md:grid-cols-2"><label class="block text-sm">允许服务器 Guild ID，一行一个<textarea v-model="guilds" class="mt-1 h-28 w-full rounded border px-3 py-2" /></label><label class="block text-sm">允许频道 Channel ID，一行一个<textarea v-model="channels" class="mt-1 h-28 w-full rounded border px-3 py-2" /></label><label class="block text-sm">允许身份组 Role ID，一行一个<textarea v-model="roles" class="mt-1 h-28 w-full rounded border px-3 py-2" /></label><label class="block text-sm">封禁 Discord 用户 ID，一行一个<textarea v-model="blocked" class="mt-1 h-28 w-full rounded border px-3 py-2" /></label></div><div class="grid gap-4 md:grid-cols-3"><label class="block text-sm">每分钟最多操作<input type="number" v-model.number="form.risk_control.max_actions_per_minute" class="mt-1 w-full rounded border px-3 py-2" /></label><label class="block text-sm">每小时最多创建订单<input type="number" v-model.number="form.risk_control.max_orders_per_hour" class="mt-1 w-full rounded border px-3 py-2" /></label><label class="block text-sm">最多未支付订单<input type="number" v-model.number="form.risk_control.max_pending_orders" class="mt-1 w-full rounded border px-3 py-2" /></label></div><button class="rounded bg-blue-600 px-4 py-2 text-white" :disabled="saving" @click="save">{{ saving?'保存中':'保存风控' }}</button></div></div></template>
