<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { adminAPI } from '@/api/admin'
const loading=ref(false), page=ref(1), total=ref(0); const pageSize=20; const items=ref<any[]>([])
async function load(){ loading.value=true; try{ const res=await adminAPI.getDiscordPaymentIssues({page:page.value,page_size:pageSize}); items.value=res.data?.data||[]; total.value=res.data?.pagination?.total||0 } finally{loading.value=false} }
async function sync(row:any){ row.syncing=true; try{ await adminAPI.syncDiscordPaymentIssue(row.payment_id); await load() } finally{ row.syncing=false } }
onMounted(load)
</script>
<template><div class="space-y-4"><div><h1 class="text-2xl font-semibold">Discord 支付异常兜底</h1><p class="text-sm text-slate-500">列出 Discord 来源的待支付订单和未确认支付，可手动同步支付平台状态。</p></div><button class="rounded bg-slate-900 px-4 py-2 text-white" @click="load">刷新</button><div class="overflow-x-auto rounded-xl border bg-white"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left"><tr><th class="p-3">订单</th><th class="p-3">支付</th><th class="p-3">用户</th><th class="p-3">金额</th><th class="p-3">操作</th></tr></thead><tbody><tr v-for="row in items" :key="row.payment_id" class="border-t"><td class="p-3"><div class="font-medium">{{ row.order_no }}</div><div class="text-xs text-slate-500">订单：{{ row.order_status }}</div></td><td class="p-3"><div>{{ row.payment_status }}</div><div class="text-xs text-slate-500">{{ row.provider_type }}/{{ row.channel_type }}</div><div class="text-xs text-slate-400">{{ row.provider_ref || row.gateway_order_no }}</div></td><td class="p-3"><div>{{ row.discord_username }}</div><div class="text-xs text-slate-500">{{ row.email }}</div></td><td class="p-3">{{ row.amount }} {{ row.currency }}</td><td class="p-3"><button class="rounded bg-blue-600 px-3 py-1.5 text-white" :disabled="row.syncing" @click="sync(row)">{{ row.syncing ? '同步中' : '手动同步' }}</button></td></tr><tr v-if="!loading && !items.length"><td colspan="5" class="p-6 text-center text-slate-500">暂无异常待处理</td></tr></tbody></table></div><div class="flex items-center justify-between text-sm"><span>共 {{ total }} 条</span><div class="space-x-2"><button class="rounded border px-3 py-1" :disabled="page<=1" @click="page--;load()">上一页</button><span>{{ page }}</span><button class="rounded border px-3 py-1" :disabled="items.length < pageSize" @click="page++;load()">下一页</button></div></div></div></template>
