// 自动生成：Discord Bot 全部交互文案词条目录（key + 分组 + 默认文案，用作标签与占位）
// 这些 key 全部写入 panel.interaction_texts，bot 端通过 b.text(key) 读取。
export interface BotTextEntry { key: string; group: string; def: string }
export const botTextCatalog: BotTextEntry[] = [
  { key: 'product_expired', group: '商品', def: '商品按钮已失效。' },
  { key: 'product_id_label', group: '商品', def: '商品 ID' },
  { key: 'product_info_expired', group: '商品', def: '商品信息已失效，请返回商品列表重新选择。' },
  { key: 'product_keyword_filter', group: '商品', def: '关键词：`%s`' },
  { key: 'product_list_choose', group: '商品', def: '请选择下方商品查看详情。' },
  { key: 'product_list_empty', group: '商品', def: '没有找到商品。' },
  { key: 'product_list_hint', group: '商品', def: '也可以直接使用下方下拉菜单查看商品详情。' },
  { key: 'product_list_page', group: '商品', def: '第 %d/%d 页' },
  { key: 'product_list_title', group: '商品', def: '🛍️ **商品列表**' },
  { key: 'product_load_failed', group: '商品', def: '读取商品信息失败' },
  { key: 'product_select_placeholder', group: '商品', def: '选择商品查看详情 / Select a product' },
  { key: 'products_label', group: '商品', def: '商品' },
  { key: 'sku_expired', group: '规格', def: '规格选择已失效。' },
  { key: 'sku_invalid', group: '规格', def: '规格选择无效。' },
  { key: 'sku_label', group: '规格', def: '规格 SKU' },
  { key: 'sku_more', group: '规格', def: '还有 %d 个规格，请到网页端查看。' },
  { key: 'sku_not_found', group: '规格', def: '规格不存在或已失效，请重新选择。' },
  { key: 'sku_select_empty', group: '规格', def: '请选择一个规格。' },
  { key: 'sku_select_invalid', group: '规格', def: '规格选择无效。' },
  { key: 'sku_select_placeholder', group: '规格', def: '选择规格 / Select SKU' },
  { key: 'qty_above_max', group: '数量', def: '购买数量不能超过最大购买数量：%d。' },
  { key: 'qty_below_min', group: '数量', def: '购买数量不能低于最小购买数量：%d。' },
  { key: 'qty_exceeds_stock', group: '数量', def: '购买数量超过当前库存，当前可购数量：%d。' },
  { key: 'qty_placeholder_default', group: '数量', def: '例如：1' },
  { key: 'qty_placeholder_max', group: '数量', def: '最多 %d' },
  { key: 'qty_placeholder_min', group: '数量', def: '最少 %d' },
  { key: 'qty_placeholder_stock', group: '数量', def: '库存 %d' },
  { key: 'quantity_invalid', group: '数量', def: '购买数量必须是大于 0 的整数。' },
  { key: 'quantity_modal_label', group: '数量', def: '购买数量 / Quantity' },
  { key: 'quantity_modal_title', group: '数量', def: '填写购买数量 / Quantity' },
  { key: 'buy_expired', group: '购买', def: '购买按钮已失效。' },
  { key: 'buy_hint', group: '购买', def: '购买' },
  { key: 'buy_quantity_button', group: '购买', def: '填写数量购买 / Buy' },
  { key: 'pay_amount_label', group: '支付', def: '支付金额' },
  { key: 'pay_expired', group: '支付', def: '支付按钮已失效。' },
  { key: 'pay_link_label', group: '支付', def: '支付链接' },
  { key: 'payment_channels_title', group: '支付', def: '订单可用支付通道' },
  { key: 'payment_contact_support', group: '支付', def: '。如已付款请联系客服。' },
  { key: 'payment_create_failed', group: '支付', def: '订单已创建，但支付发起失败' },
  { key: 'payment_failed_title', group: '支付', def: '订单支付未成功' },
  { key: 'payment_final_status', group: '支付', def: '最终状态' },
  { key: 'payment_initiated_title', group: '支付', def: '支付已发起' },
  { key: 'payment_status_canceled', group: '支付', def: '已取消' },
  { key: 'payment_status_expired', group: '支付', def: '已过期' },
  { key: 'payment_status_failed', group: '支付', def: '支付失败' },
  { key: 'payment_status_paid', group: '支付', def: '已支付' },
  { key: 'payment_status_pending', group: '支付', def: '待确认' },
  { key: 'payment_status_unknown', group: '支付', def: '未知' },
  { key: 'payment_success', group: '支付', def: '支付成功' },
  { key: 'payment_wait_hint', group: '支付', def: '支付完成后，Bot 会自动通知；也可以点下面按钮刷新订单状态。' },
  { key: 'order_create_failed', group: '订单', def: '创建订单失败' },
  { key: 'order_created_title', group: '订单', def: '订单已创建' },
  { key: 'order_detail_failed', group: '订单', def: '获取订单详情失败，请使用 /orders 查看' },
  { key: 'order_id_label', group: '订单', def: '订单 ID' },
  { key: 'order_lookup_button', group: '订单', def: '查询订单' },
  { key: 'order_modal_label', group: '订单', def: '订单号 / Order No.' },
  { key: 'order_modal_placeholder', group: '订单', def: '请输入订单号' },
  { key: 'order_modal_title', group: '订单', def: '查询订单 / Order Lookup' },
  { key: 'order_no_label', group: '订单', def: '订单号' },
  { key: 'order_not_paid', group: '订单', def: '订单尚未支付或未完成。' },
  { key: 'order_paid_processing', group: '订单', def: '订单已支付，发货处理中。稍后刷新订单状态。' },
  { key: 'order_query_failed', group: '订单', def: '查询失败' },
  { key: 'order_select_expired', group: '订单', def: '订单选择已失效。' },
  { key: 'order_select_placeholder', group: '订单', def: '选择订单查看商品与发货内容 / Select an order' },
  { key: 'order_shipped_hint', group: '订单', def: '请刷新订单状态查看交付内容。' },
  { key: 'order_shipped_title', group: '订单', def: '订单已发货' },
  { key: 'order_status_title', group: '订单', def: '订单状态' },
  { key: 'order_too_frequent', group: '订单', def: '创建订单太频繁，请稍后再试。' },
  { key: 'orders_page', group: '订单', def: '第 %d/%d 页' },
  { key: 'orders_status_filter', group: '订单', def: '状态筛选：`%s`' },
  { key: 'orders_title', group: '订单', def: '📦 我的订单' },
  { key: 'profile_bind_failed', group: '账号设置', def: '绑定失败' },
  { key: 'profile_edit_button', group: '账号设置', def: '设置/修改邮箱与查询密码' },
  { key: 'profile_email_label', group: '账号设置', def: '邮箱 / Email' },
  { key: 'profile_info', group: '账号设置', def: 'ç«åç¨æ·IDï¼`%d`\nç»å®é®ç®±ï¼`%s`\næ¥è¯¢å¯ç ï¼||%s||\nè¯­è¨ï¼%s (`%s`)' },
  { key: 'profile_language_button', group: '账号设置', def: '语言 / Language' },
  { key: 'profile_load_failed', group: '账号设置', def: '读取账号设置失败' },
  { key: 'profile_modal_title', group: '账号设置', def: '绑定邮箱与查询密码' },
  { key: 'profile_not_bound', group: '账号设置', def: '当前还没有绑定邮箱与查询密码。请点击下方按钮设置。' },
  { key: 'profile_password_hint', group: '账号设置', def: '用于查询游客订单' },
  { key: 'profile_password_label', group: '账号设置', def: '查询密码 / Order Password' },
  { key: 'profile_password_unset', group: '账号设置', def: '未设置' },
  { key: 'profile_required', group: '账号设置', def: '⚠️ 请先绑定邮箱与查询密码。提交后系统会自动创建/绑定站内用户并自动通过邮箱验证，之后通过 Bot 创建的订单会归属到这个用户。' },
  { key: 'profile_title', group: '账号设置', def: '👤 **账号设置**' },
  { key: 'wallet_amount_label', group: '钱包充值', def: '充值金额 / Amount' },
  { key: 'wallet_amount_positive', group: '钱包充值', def: '充值金额必须大于 0' },
  { key: 'wallet_amount_too_large', group: '钱包充值', def: '充值金额过大，请联系管理员' },
  { key: 'wallet_balance', group: '钱包充值', def: '当前余额' },
  { key: 'wallet_balance_after', group: '钱包充值', def: '余额' },
  { key: 'wallet_channel_invalid', group: '钱包充值', def: '支付通道无效。' },
  { key: 'wallet_channels_failed', group: '钱包充值', def: '读取钱包充值支付通道失败' },
  { key: 'wallet_enter_amount', group: '钱包充值', def: '请输入充值金额' },
  { key: 'wallet_no_channels', group: '钱包充值', def: '当前没有可用于钱包充值的支付通道，请联系管理员。' },
  { key: 'wallet_no_txns', group: '钱包充值', def: '暂无钱包明细。' },
  { key: 'wallet_not_paid_yet', group: '钱包充值', def: '暂时还没有检测到付款成功，请确认已完成付款后，稍后再点击刷新充值状态。' },
  { key: 'wallet_pay_done_hint', group: '钱包充值', def: '已使用余额完成支付，输入 `/order` 查看发卡内容。' },
  { key: 'wallet_pay_link', group: '钱包充值', def: '支付链接' },
  { key: 'wallet_pay_success', group: '钱包充值', def: '已使用余额完成支付' },
  { key: 'wallet_payment_id_invalid', group: '钱包充值', def: '充值支付编号无效。' },
  { key: 'wallet_qr_content', group: '钱包充值', def: '二维码/收款内容' },
  { key: 'wallet_recent', group: '钱包充值', def: '最近明细' },
  { key: 'wallet_recharge_amount', group: '钱包充值', def: '本次充值' },
  { key: 'wallet_recharge_amount_label', group: '钱包充值', def: '金额' },
  { key: 'wallet_recharge_arrived', group: '钱包充值', def: '钱包充值已到账' },
  { key: 'wallet_recharge_created', group: '钱包充值', def: '钱包充值已创建' },
  { key: 'wallet_recharge_done', group: '钱包充值', def: '✅ 充值已到账。' },
  { key: 'wallet_recharge_expired', group: '钱包充值', def: '充值按钮已失效。' },
  { key: 'wallet_recharge_failed', group: '钱包充值', def: '充值创建失败' },
  { key: 'wallet_recharge_failed_notify', group: '钱包充值', def: '钱包充值未成功，如已付款请联系客服。最终状态' },
  { key: 'wallet_recharge_hint', group: '钱包充值', def: '可以选择下方金额快速充值，也可以自定义金额。' },
  { key: 'wallet_recharge_hint_after', group: '钱包充值', def: '充值成功后，Bot 会自动通知；也可以返回钱包查看余额。' },
  { key: 'wallet_recharge_no', group: '钱包充值', def: '充值单号' },
  { key: 'wallet_recharge_status', group: '钱包充值', def: '状态' },
  { key: 'wallet_recharge_success', group: '钱包充值', def: '✅ 充值已到账，请返回钱包刷新余额。' },
  { key: 'wallet_recharge_success_title', group: '钱包充值', def: '钱包充值成功' },
  { key: 'wallet_recharge_title', group: '钱包充值', def: '钱包充值 / Wallet Recharge' },
  { key: 'wallet_select_amount', group: '钱包充值', def: '请选择充值金额。' },
  { key: 'wallet_status_contact', group: '钱包充值', def: '充值支付状态：%s。如已付款，请联系客服处理。' },
  { key: 'wallet_status_expired', group: '钱包充值', def: '充值状态按钮已失效。' },
  { key: 'wallet_status_pending', group: '钱包充值', def: '充值支付状态：%s。如果你刚刚完成付款，请等待几秒后再次点击刷新。' },
  { key: 'wallet_title', group: '钱包充值', def: '💰 我的钱包' },
  { key: 'language_bind_first', group: '语言', def: '请先在账号设置里绑定邮箱和查询密码，然后再保存语言。' },
  { key: 'language_current', group: '语言', def: '当前语言' },
  { key: 'language_placeholder', group: '语言', def: '选择语言 / Choose language' },
  { key: 'language_save_failed', group: '语言', def: '保存语言失败' },
  { key: 'language_select_prompt', group: '语言', def: '请选择一种语言。' },
  { key: 'language_title', group: '语言', def: '🌐 语言设置 / Language' },
  { key: 'language_updated', group: '语言', def: '语言已更新' },
  { key: 'help_support_label', group: '帮助', def: '客服：%s' },
  { key: 'help_title', group: '帮助', def: '❓ Discord 帮助中心' },
  { key: 'no_help_content', group: '帮助', def: '暂无帮助内容。' },
  { key: 'delivery_instructions', group: '发货/交付', def: '说明' },
  { key: 'delivery_title', group: '发货/交付', def: '交付内容' },
  { key: 'back_button', group: '按钮', def: '返回' },
  { key: 'back_product_list_button', group: '按钮', def: '返回商品列表' },
  { key: 'btn_all_orders', group: '按钮', def: '全部订单' },
  { key: 'btn_back', group: '按钮', def: '返回' },
  { key: 'btn_back_wallet', group: '按钮', def: '返回钱包' },
  { key: 'btn_custom_amount', group: '按钮', def: '自定义金额' },
  { key: 'btn_next_page', group: '按钮', def: '下一页' },
  { key: 'btn_paid_refresh', group: '按钮', def: '我已付款，刷新充值状态' },
  { key: 'btn_pending_payment', group: '按钮', def: '待支付' },
  { key: 'btn_prev_page', group: '按钮', def: '上一页' },
  { key: 'btn_refresh_balance', group: '按钮', def: '刷新余额' },
  { key: 'btn_refresh_status', group: '按钮', def: '刷新订单状态' },
  { key: 'next_page_button', group: '按钮', def: '下一页' },
  { key: 'prev_page_button', group: '按钮', def: '上一页' },
  { key: 'quick_order_hint', group: '选择/快捷', def: '请点击面板里的「查询订单」按钮，输入订单号后查询。' },
  { key: 'quick_unavailable', group: '选择/快捷', def: '这个快捷功能暂不可用。' },
  { key: 'select_function', group: '选择/快捷', def: '请选择一个功能。' },
  { key: 'select_order', group: '选择/快捷', def: '请选择一个订单。' },
  { key: 'select_payment_channel', group: '选择/快捷', def: '请选择支付通道' },
  { key: 'select_product', group: '选择/快捷', def: '请选择一个商品。' },
  { key: 'select_sku', group: '选择/快捷', def: '请选择一个规格。' },
  { key: 'select_sku_first', group: '选择/快捷', def: '这个商品有多个规格，请先选择 SKU。' },
  { key: 'panel_expired', group: '面板', def: '面板按钮已失效。' },
  { key: 'panel_refresh_not_found', group: '面板', def: '未找到可刷新的面板消息。' },
  { key: 'panel_refreshed', group: '面板', def: '✅ 面板已刷新。' },
  { key: 'bot_disabled', group: '风控/限制', def: 'Discord Bot 当前未启用，请联系管理员。' },
  { key: 'pending_orders_limit', group: '风控/限制', def: '你当前有 %d 个待支付订单，请先完成支付或取消后再下单。' },
  { key: 'restrict_blocked_user', group: '风控/限制', def: '你的 Discord 账号已被限制使用 Bot。' },
  { key: 'restrict_channel', group: '风控/限制', def: '这个 Bot 已限制在指定频道使用。' },
  { key: 'restrict_guild', group: '风控/限制', def: '这个 Bot 未开放给当前服务器使用。' },
  { key: 'restrict_rate_limit', group: '风控/限制', def: '操作太频繁，请稍后再试。' },
  { key: 'restrict_role', group: '风控/限制', def: '你的 Discord 身份组暂时没有使用该 Bot 的权限。' },
  { key: 'amount_label', group: '通用', def: '金额' },
  { key: 'button_expired', group: '通用', def: '按钮已失效。' },
  { key: 'category_label', group: '通用', def: '分类' },
  { key: 'channel_label', group: '通用', def: '通道' },
  { key: 'enter_order_no', group: '通用', def: '请输入订单号。' },
  { key: 'form_not_supported', group: '通用', def: '⚠️ 这个商品需要填写额外表单，Discord Bot 暂不支持复杂表单，请到网页端下单。' },
  { key: 'form_required_hint', group: '通用', def: '这个商品需要填写额外表单，当前 Discord Bot 暂未支持复杂表单，请到网页端下单。' },
  { key: 'fulfillment_type_label', group: '通用', def: '发货类型' },
  { key: 'member_price_suffix', group: '通用', def: '会员价' },
  { key: 'modal_expired', group: '通用', def: '表单已失效。' },
  { key: 'no_orders', group: '通用', def: '暂无订单。' },
  { key: 'no_payment_channels', group: '通用', def: '当前没有可用支付通道。' },
  { key: 'no_products', group: '通用', def: '没有找到商品。' },
  { key: 'operation_failed', group: '通用', def: '操作失败' },
  { key: 'or_use_command', group: '通用', def: '也可以使用按钮，或输入' },
  { key: 'paid_amount_label', group: '通用', def: '已付' },
  { key: 'price_label', group: '通用', def: '价格' },
  { key: 'qrcode_label', group: '通用', def: '二维码/收款内容' },
  { key: 'retry_payment', group: '通用', def: '重新发起支付' },
  { key: 'status_expired', group: '通用', def: '状态按钮已失效。' },
  { key: 'status_label', group: '通用', def: '状态' },
  { key: 'stock_label', group: '通用', def: '库存' },
  { key: 'unsupported_command', group: '通用', def: '暂不支持这个命令。' },
]

export const botTextGroups = ["商品", "规格", "数量", "购买", "支付", "订单", "账号设置", "钱包充值", "语言", "帮助", "发货/交付", "按钮", "选择/快捷", "面板", "风控/限制", "通用"] as const